### ISSUE TITLE
what is the difference between “union_label_id” and “parse_label_id” in "coco_train_rmcocodev_ram.json"?

### ISSUE THREAD

**Issue by SANJINGSHOU14** [xinyu1205/recognize-anything#108]
Thanks for your great work, i have some questions about the label: what is the difference between “union_label_id” and “parse_label_id” in "coco_train_rmcocodev_ram.json"?

**Comment by xinyu1205** [comment]
'parse_label_id' refers to the image tags parsed from image text, as detail in Tag2Text paper.
'union_label_id' refers to on the basic of 'parse_label_id', the image tags are further augmented via the automated data engine of RAM paper.

**Comment by SANJINGSHOU14** [comment]
thanks for your answer.

> 
further augmented via the automated data engine of RAM paper
> 
here the "automated data engine" means, use the RAM model to get the image tags?

**Comment by SANJINGSHOU14** [comment]
> 'parse_label_id' refers to the image tags parsed from image text, as detail in Tag2Text paper. 'union_label_id' refers to on the basic of 'parse_label_id', the image tags are further augmented via the automated data engine of RAM paper.

Thanks your answer. 
Here the "automated data engine" means that we use the RAM model to get the image tags, then the result is the "union_label_id"?

**Comment by xinyu1205** [comment]
"automated data engine" is used to enhance parsed tags, details are in RAM paper.
