### ISSUE TITLE
erros of finetune ram plus model in another dataset

### ISSUE THREAD

**Issue by stoensin** [xinyu1205/recognize-anything#110]
### Background Introduction

I use the **fashion_gen** dataset to fine-tune the **ram plus** model. The dataset size is **260,490** and the class label size is **40,898**.

!python finetune.py \
  --model-type ram_plus \
  --config ram/configs/finetune.yaml  \
  --checkpoint CKPT/ram_plus_swin_large_14m.pth \
  --output-dir outputs/ram_plus_ft
 
 the error below:
 ```
Not using distributed mode
Creating dataset
loading dataspaces/train.json
number of training samples: 260490
Creating model
load from: /data/CKPT/sam_ckpt/ram_plus_swin_large_14m.pth
Creating pretrained CLIP model
Creating RAM model
{'image_size': 384, 'vit': 'swin_l', 'vit_grad_ckpt': False, 'vit_ckpt_layer': 0}
--------------
/data/CKPT/sam_ckpt/ram_plus_swin_large_14m.pth
--------------
torch.Size([233835, 512])
Traceback (most recent call last):
  File "dataspaces/finetune.py", line 284, in <module>
    main(args, config)
  File "dataspaces/finetune.py", line 201, in main
    model = ram_plus(pretrained = args.checkpoint,image_size=config['image_size'], vit=config['vit'], vit_grad_ckpt=config['vit_grad_ckpt'], 
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dataspaces/ram/models/ram_plus.py", line 401, in ram_plus
    model, msg = load_checkpoint_swinlarge(model, pretrained, kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dataspaces/ram/models/utils.py", line 274, in load_checkpoint_swinlarge
    msg = model.load_state_dict(state_dict, strict=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RAM_plus:
	size mismatch for label_embed: copying a param with shape torch.Size([233835, 512]) from checkpoint, the shape in current model is torch.Size([2085798, 512]).
```

Can you give me some suggestions on how to modify the code so that fintune can proceed smoothly?

**Comment by xinyu1205** [comment]
Sorry for not responding quickly due to my busy schedule.
This error is because you utilized the original 4,585 label embedding of RAM++.
If you want to fine tune RAM/RAM++on the customer dataset, you need to generate corresponding label embeddings based on the categories you need to recognize. You can refer to the unseen categories inference of RAM/RAM++.
Best wishes.

**Comment by stoensin** [comment]
> Sorry for not responding quickly due to my busy schedule. This error is because you utilized the original 4,585 label embedding of RAM++. If you want to fine tune RAM/RAM++on the customer dataset, you need to generate corresponding 40,898 label embeddings based on the categories you need to recognize. You can refer to the unseen categories inference of RAM/RAM++. Best wishes.

Yeah, I understand. Before that i have successfully run finetune.py by adding the following code to [this file](https://github.com/xinyu1205/recognize-anything/blob/054769e67dbdd1aa6ad248fb8194eafb3341bb0b/ram/models/utils.py#L273):
```
    if 'label_embed' in state_dict:
        del state_dict['label_embed']
```
so maybe that's not a good idea, is it?

**Comment by xinyu1205** [comment]
That's right, you should delete the label_embed in [state_dict] of released RAM/RAM++ checkpoint.
You should also generate the corresponding label_embed for your own categories.

**Comment by adbmdp** [comment]
Hello @stoensin,
Did you manage to finetune the model? If so, did you have good results?
Thanks! 🙏
