### ISSUE TITLE
About the merging tags step in paper "Recognize Anything: A Strong Image Tagging Model".

### ISSUE THREAD

**Issue by xin-ran-w** [xinyu1205/recognize-anything#112]
Hello, author, I noticed you have the merging tags step in RAM's paper (section 3.1). I wonder if there is any way to map the tag to the wordnet synset, which means the RAM can directly predict synset.

**Comment by xinyu1205** [comment]
Hi, 我们发现Wordnet中的同义词映射存在较多的noise。因此在标签类别合并阶段，人工校验占了较大的比重。

如果无法确定要想识别的类别是否存在在RAM标签体系中：
我认为一种直接的方法是，参考RAM在unseen类别上的测试，统一将要识别的所有类别直接转换成tag embeddings，[build_openset_label_embedding](https://github.com/xinyu1205/recognize-anything/blob/main/ram/utils/openset_utils.py)，RAM有一定的同义词处理能力。
另外一种办法是，可以通过GPT api检查是否可以将需要识别的类别映射到[RAM的标签列表](https://github.com/xinyu1205/recognize-anything/blob/main/ram/data/ram_tag_list.txt)。

希望可以帮助到你。

**Comment by xin-ran-w** [comment]
感谢！
