### ISSUE TITLE
what's the meaning of the "loss_dis"?

### ISSUE THREAD

**Issue by SANJINGSHOU14** [xinyu1205/recognize-anything#113]
In RAM model, I have some trouble with understanding the role of the "loss_dis".

**Comment by xinyu1205** [comment]
It mains the distillation loss.
You can refer to RAM++ paper, and below issue.
https://github.com/xinyu1205/recognize-anything/issues/94

**Comment by SANJINGSHOU14** [comment]
Thanks for your answer, I have understood the meaning of "Loss_dis".
