### ISSUE TITLE
How to define the threshold of each tag in tag list if I want to pretrain RAM on a new dataset?

### ISSUE THREAD

**Issue by SANJINGSHOU14** [xinyu1205/recognize-anything#115]
I want to know how to decide the threshold of each tag in the tag list? Maybe by occurrence frequency？

**Comment by xinyu1205** [comment]
The default threshold for RAM is 0.68, for new categories, you need to evaluate in your own test set.
https://github.com/xinyu1205/recognize-anything/issues/45

**Comment by SANJINGSHOU14** [comment]
Thanks for your answer, that is a hard work.

**Comment by fmy7834** [comment]
> The default threshold for RAM is 0.68, for new categories, you need to evaluate in your own test set. #45
I remember the default threshold is 0.86 in early version code of RAM. Am I remembering it wrong?

**Comment by xinyu1205** [comment]
> > > The default threshold for RAM is 0.68, for new categories, you need to evaluate in your own test set. #45
> 
> **I remember the default threshold is 0.86 in early version code of RAM. Am I remembering it wrong?**

Hi, sorry for the confusion.
We set a unified threshold of **0.86** for RAM in Table 3 of the RAM paper, as there are misses labels in the test sets and often requires a higher threshold for better Precision metric.
In the use of demo, we lower the default threshold to **0.65** to improve the diversity of its outputs. https://github.com/xinyu1205/recognize-anything/blob/main/ram/data/ram_tag_list_threshold.txt

**Comment by fmy7834** [comment]
Got it. Thank you for your reply.
