### ISSUE TITLE
Open-set Tagging

### ISSUE THREAD

**Issue by EduardoPach** [xinyu1205/recognize-anything#125]
To do open-set tagging one needs to:

1. Compute the `CLIP` embeddings
2. Already have some tags in mind and enhance with `GPT-3.5`
3. Override some attributes in `RAM++` and run the `generate_tag_openset` (which is exactly the same as `generate_tag`)

Is that correct?

**Comment by xinyu1205** [comment]
Hi, I have optimized your summary:
1. Already have some tags in mind and enhance into tag descriptions with GPT-3.5
2. Compute the tag descriptions embeddings using CLIP text encoder
3. Replace the label_embed of RAM++ with the computed tag descriptions embeddings

**Comment by EduardoPach** [comment]
> Hi, I have optimized your summary:
> 
> 1. Already have some tags in mind and enhance into tag descriptions with GPT-3.5
> 
> 2. Compute the tag descriptions embeddings using CLIP text encoder
> 
> 3. Replace the label_embed of RAM++ with the computed tag descriptions embeddings

Ops, inverted the orders from 1. And 2. Thanks for the quick answer!
