### ISSUE TITLE
Confusion about spatial embeddings in ram_plus!

### ISSUE THREAD

**Issue by stoensin** [xinyu1205/recognize-anything#127]
during forward steps:
[image_spatial_embeds](https://github.com/xinyu1205/recognize-anything/blob/97a867ef8a453e71e956b8ca8dfa24103d84f25d/ram/models/ram_plus.py#L209)
and 
[bs](https://github.com/xinyu1205/recognize-anything/blob/97a867ef8a453e71e956b8ca8dfa24103d84f25d/ram/models/ram_plus.py#L214)
the image_spatial_embeds is set but not use
<img width="745" alt="image" src="https://github.com/xinyu1205/recognize-anything/assets/8474954/05e4c334-5574-493c-a96a-224eafdfc88d">

then during generate_tag steps:
[image_spatial_embeds](https://github.com/xinyu1205/recognize-anything/blob/97a867ef8a453e71e956b8ca8dfa24103d84f25d/ram/models/ram_plus.py#L278)
and 
[bs](https://github.com/xinyu1205/recognize-anything/blob/97a867ef8a453e71e956b8ca8dfa24103d84f25d/ram/models/ram_plus.py#L280)
<img width="887" alt="image" src="https://github.com/xinyu1205/recognize-anything/assets/8474954/f18a9de7-024c-4630-b0a2-d900e741e460">

Why does "image_spatial_embeds" not participate in the calculation in forward?

**Comment by xinyu1205** [comment]
Hi, we directly utilize image_embeds, which includes both image_cls_embeds and image_spatial_embeds.
