### ISSUE TITLE
How to fine-tune Tag2Text with custom tags?

### ISSUE THREAD

**Issue by SeeknnDestroy** [xinyu1205/recognize-anything#143]
Hi @xinyu1205, thank you very much for your work!

Can you please briefly explain how can I finetune tag2text model with my custom 100 labels that are not included in `tag2text_ori_tag_list.txt`?

1-Should I add them on top of `tag2text_ori_tag_list.txt` and proceed with total of 3429+100 tags?
2-Do I need to create any extra mapping file between `tag_list` and `tag_ids`? Or `tag_list.txt` is sufficient?
3-Any ordering rule in `tag_list.txt`?
4-In my `train_dataset` json file, should I include both `union_label_id` and `parse_label_id`?
5-If so, can you please give example on how should I construct each of those? And their difference?

**Comment by xinyu1205** [comment]
Hi, thanks for your attention.

Let me to briefly explain how to finetune Tag2Text on your custom 100 labels.

1. Replace tag2text_ori_tag_list.txt into custom_100_tag_list.txt. And there is no need for any ordering rules.
2. Load Tag2Text checkpoint, but reinitialize` self.fc`, `self.label_embed` and `self.class_threshold`, because they are related to tag list.
3. Set your own train_dataset, only "`image`", "`text`" and "`tags parsed from text (parse_label_id)`" are needed.
4. Start training.

There may be some details that need to be modified, please feel free to provide feedback.

**Comment by fcakyon** [comment]
Thanks for the detailed answer @xinyu1205 !

What should be the relation between custom_100_tag_list.txt and List[parse_label_id]? How should I map the label ids to a list of tag? Is the ids simply the order index of the tags from the txt file?

Bests

**Comment by xinyu1205** [comment]
Hi, thanks for your attention.
The reason is that the data reading class needs to support both Tag2Text and RAM, while RAM requires the `union_parse_id` of `image_tag`. Therefore, if you only fine-tune Tag2Text, you can delete the `image_tag` in https://github.com/xinyu1205/recognize-anything/blob/dc5402256107b78bc256b8cf0f251a5c89558560/ram/data/dataset.py#L57
Because the forward of Tag2Text only requires image, caption, and parse_tag.
https://github.com/xinyu1205/recognize-anything/blob/dc5402256107b78bc256b8cf0f251a5c89558560/ram/models/tag2text.py#L153

Please feel free to provide any feedback.

**Comment by fcakyon** [comment]
@xinyu1205 A better solution would be making these lines optional:

https://github.com/xinyu1205/recognize-anything/blob/dc5402256107b78bc256b8cf0f251a5c89558560/ram/data/dataset.py#L43-L46

as:

```python 
if ann.get('union_label_id') is not None:
    num = ann['union_label_id'] 
    image_tag = np.zeros([self.class_num]) 
    image_tag[num] = 1 
    image_tag = torch.tensor(image_tag, dtype = torch.long)
else:
    image_tag = None
```

Then the whole code base could be used on all architecture types without any code modification.

What do you think? @xinyu1205

**Comment by xinyu1205** [comment]
It's a great modification!
We warmly welcome you to submit your PR as a contributor.

**Comment by pribadihcr** [comment]
> Hi, thanks for your attention.
> 
> Let me to briefly explain how to finetune Tag2Text on your custom 100 labels.
> 
> 1. Replace tag2text_ori_tag_list.txt into custom_100_tag_list.txt. And there is no need for any ordering rules.
> 2. Load Tag2Text checkpoint, but reinitialize` self.fc`, `self.label_embed` and `self.class_threshold`, because they are related to tag list.
> 3. Set your own train_dataset, only "`image`", "`text`" and "`tags parsed from text (parse_label_id)`" are needed.
> 4. Start training.
> 
> There may be some details that need to be modified, please feel free to provide feedback.

Hi, how to re-initialize self.fc, self.label_embed? I got the following error:

```
    model, msg = load_checkpoint_swinbase(model, pretrained, kwargs)
  File "../recognize-anything/ram/models/utils.py", line 271, in load_checkpoint_swinbase
    msg = model.load_state_dict(state_dict, strict=False)
  File "../lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Tag2Text:
	size mismatch for label_embed.weight: copying a param with shape torch.Size([118, 768]) from checkpoint, the shape in current model is torch.Size([3429, 768]).
	size mismatch for fc.W: copying a param with shape torch.Size([1, 118, 768]) from checkpoint, the shape in current model is torch.Size([1, 3429, 768]).
	size mismatch for fc.b: copying a param with shape torch.Size([1, 118]) from checkpoint, the shape in current model is torch.Size([1, 3429]).

```
number of my custom tags is 118. Thanks

**Comment by xinyu1205** [comment]
For self. label_embed, you can select the overlapping categories and randomly initialize other categories. 
For self.fc, perhaps you can directly try using random initialization and see the performance.

**Comment by pribadihcr** [comment]
Hi @xinyu1205 

I have tried modified the function load_checkpoint_swinbase in ram.models.utils 

```
def load_checkpoint_swinbase(model, url_or_filename, kwargs):
    if kwargs['image_size'] == 224:
        vision_config_path = f'{CONFIG_PATH}/configs/swin/config_swinB_224.json'
    elif kwargs['image_size'] == 384:
        vision_config_path = f'{CONFIG_PATH}/configs/swin/config_swinB_384.json'
    window_size = read_json(vision_config_path)['window_size']
    print('--------------')
    print(url_or_filename)
    print('--------------')
    if is_url(url_or_filename):
        cached_file = download_cached_file(url_or_filename,
                                           check_hash=False,
                                           progress=True)
        checkpoint = torch.load(cached_file, map_location='cpu')
    elif os.path.isfile(url_or_filename):
        checkpoint = torch.load(url_or_filename, map_location='cpu')
    else:
        raise RuntimeError('checkpoint url or path is invalid')

    state_dict = checkpoint['model']

    for k in list(state_dict.keys()):
        if 'relative_position_bias_table' in k:
            dst_num_pos = (2 * window_size - 1)**2
            state_dict[k] = interpolate_relative_pos_embed(state_dict[k],
                                                           dst_num_pos,
                                                           param_name=k)
        elif ('relative_position_index' in k) or ('attn_mask' in k):
            del state_dict[k]
        elif "vision_multi" in k:
            state_dict[k.replace("vision_multi",
                                 "tagging_head")] = state_dict.pop(k)

    if "fc.W" in state_dict.keys():
        state_dict["fc.W"] = torch.nn.Parameter(torch.Tensor(1, 118, 768))
        state_dict["fc.b"]= nn.Parameter(torch.Tensor(1, 118))
        
        stdv = 1. / math.sqrt(state_dict["fc.W"].size(2))
        for i in range(118):
            state_dict["fc.W"][0][i].data.uniform_(-stdv, stdv)
        for i in range(118):
            state_dict["fc.b"][0][i].data.uniform_(-stdv, stdv)

    idx_slice = range(0, 58)
    
    overlap_label_embed_weight = state_dict["label_embed.weight"][idx_slice,:]
    new_label_embed_weight = torch.nn.Parameter(torch.Tensor(60, 768))
    trunc_normal_(new_label_embed_weight, std=.02)
    state_dict["label_embed.weight"] = torch.cat((overlap_label_embed_weight, new_label_embed_weight), 0)

    msg = model.load_state_dict(state_dict, strict=False)

    print('load checkpoint from %s' % url_or_filename)
    return model, msg
```

I have 118 tags. 58 has overlap tags with tag2text_ori_tag_list. So, I select the 58 overlapping label_embed and initialize the others 60 tags. 

The training logs epoch-0:
```
Start training
Train Epoch: [0]  [  0/540]  eta: 0:13:34  lr: 0.000005  loss_t2t: 7.5310  loss_tag: 3.4745  time: 1.5078  data: 0.3322  max mem: 7248
Train Epoch: [0]  [ 50/540]  eta: 0:02:50  lr: 0.000005  loss_t2t: 4.8541  loss_tag: 2.9228  time: 0.3251  data: 0.0001  max mem: 8582
Train Epoch: [0]  [100/540]  eta: 0:02:30  lr: 0.000005  loss_t2t: 4.4326  loss_tag: 2.4094  time: 0.3416  data: 0.0001  max mem: 8588
Train Epoch: [0]  [150/540]  eta: 0:02:14  lr: 0.000005  loss_t2t: 4.5839  loss_tag: 3.2434  time: 0.3640  data: 0.0002  max mem: 8594
Train Epoch: [0]  [200/540]  eta: 0:01:57  lr: 0.000005  loss_t2t: 4.7838  loss_tag: 2.8597  time: 0.3534  data: 0.0002  max mem: 8594
Train Epoch: [0]  [250/540]  eta: 0:01:40  lr: 0.000005  loss_t2t: 4.3246  loss_tag: 3.6409  time: 0.3386  data: 0.0001  max mem: 8602
Train Epoch: [0]  [300/540]  eta: 0:01:22  lr: 0.000005  loss_t2t: 4.5905  loss_tag: 2.9804  time: 0.3394  data: 0.0001  max mem: 8602
Train Epoch: [0]  [350/540]  eta: 0:01:05  lr: 0.000005  loss_t2t: 4.4164  loss_tag: 3.0514  time: 0.3415  data: 0.0001  max mem: 8602
Train Epoch: [0]  [400/540]  eta: 0:00:48  lr: 0.000005  loss_t2t: 4.3750  loss_tag: 3.1365  time: 0.3414  data: 0.0001  max mem: 8602
Train Epoch: [0]  [450/540]  eta: 0:00:30  lr: 0.000005  loss_t2t: 4.5714  loss_tag: 3.3215  time: 0.3325  data: 0.0001  max mem: 8602
Train Epoch: [0]  [500/540]  eta: 0:00:13  lr: 0.000005  loss_t2t: 3.6102  loss_tag: 3.7241  time: 0.3433  data: 0.0001  max mem: 8602
Train Epoch: [0]  [539/540]  eta: 0:00:00  lr: 0.000005  loss_t2t: 3.8103  loss_tag: 3.1811  time: 0.3368  data: 0.0001  max mem: 8602
Train Epoch: [0] Total time: 0:03:05 (0.3430 s / it)
Averaged stats: lr: 0.0000  loss_t2t: 4.5019  loss_tag: 3.1140
```

Is this the correct way? thanks
