### ISSUE TITLE
Weights for SWIN_B/SWIN_T

### ISSUE THREAD

**Issue by jurijsnazarovsambientai** [xinyu1205/recognize-anything#144]
Hi @xinyu1205 , Thanks for the projects, it is really great. I noticed that you published weights for SWIN_L image encoder. Could you publish it for SWIN_B or SWIN_T? Or maybe you have a data available so that I can retrain the model for SWIN_B/SWIN_T? 

Jurijs

**Comment by xinyu1205** [comment]
Personally, I would like to release all model weights, but they are stored within the company and opening source them requires sufficient justification and strict review. Therefore, there are no plans to open smaller model versions.
For data, we have open source 4M training dataset.

**Comment by jurijsnazarovsambientai** [comment]
Thanks!
