### ISSUE TITLE
Wrong pre-trained weights for image encoder

### ISSUE THREAD

**Issue by jurijsnazarovsambientai** [xinyu1205/recognize-anything#145]
Hi,

In this file: [ram/configs/swin/config_swinL_224.json](https://github.com/xinyu1205/recognize-anything/blob/dc5402256107b78bc256b8cf0f251a5c89558560/ram/configs/swin/config_swinL_224.json#L4)
you state `"ckpt": "pretrain_model/swin_large_patch4_window12_384_22k.pth",` but should not it be another model, with window7_224. If yes, where can we get this pretrained weights?

Jurijs

**Comment by xinyu1205** [comment]
Hi, thanks so much for correcting the mistake once again.
The "ckpt" in [ram/configs/swin/config_swinL_224.json](https://github.com/xinyu1205/recognize-anything/blob/dc5402256107b78bc256b8cf0f251a5c89558560/ram/configs/swin/config_swinL_224.json#L4) should set: `"ckpt":"pretrain_model/swin_large_patch4_window7_224_22k.pth"`.
You can also get it in https://github.com/microsoft/Swin-Transformer

**Comment by jurijsnazarovsambientai** [comment]
Thanks!
