### ISSUE TITLE
Tags categories

### ISSUE THREAD

**Issue by Fa-ti-ma** [xinyu1205/recognize-anything#150]
Thank you for the amazing work!
Regarding the tags used in RAM++ and tag2text. Can we have the mapping of the categories, I mean if the tags belong to attributes, objects, action etc. In Tag2text paper, table 7 provides some statistics. How do you determine this categorization?

**Comment by xinyu1205** [comment]
In `ram/data/tag2text_ori_tag_list.txt` of 3429 categories, the first 3012 categories are object/scene, the middle 240 categories are action, and the last 177 categories are attribution.
For the RAM tag list of 4585 categories, we don't classify the categories. You can classify them by GPT.
