### ISSUE TITLE
Number of tags and class_num is different by 1

### ISSUE THREAD

**Issue by jurijsnazarovsambientai** [xinyu1205/recognize-anything#151]
Hello,

I saw that `ram/data/ram_tag_list.txt` contains 4584 tags, while `class_num` equals to 4585. What is that extra 1 in `class_num` compare to number of tags in the file? 

Jurijs

**Comment by xinyu1205** [comment]
`ram/data/ram_tag_list.txt` contains 4585 tags

**Comment by jurijsnazarovsambientai** [comment]
Yes, my bad. I used `wc -l ram/data/ram_tag_list.txt`, and it counts `\n`, rather than lines. Thanks!
