### ISSUE TITLE
[Illustration] How to draw a radar chart like the one in the RAM paper?

### ISSUE THREAD

**Issue by lartpang** [xinyu1205/recognize-anything#156]
@xinyu1205 

![](https://recognize-anything.github.io/static/images/category_distribution.jpg)

The form of this radar chart is a bit unusual and I really like it.
Would you be able to provide the relevant code?
Thanks!

**Comment by xinyu1205** [comment]
Hi, this figure was actually drawn using the PowerPoint, since the proportions drawn with code are not coordinated.

**Comment by lartpang** [comment]
@xinyu1205 

Okay. Thank you for your response.
