### ISSUE TITLE
Effect commit b85a8770a8c75bd7a508e97a328ebea7444917b7 

### ISSUE THREAD

**Issue by pribadihcr** [xinyu1205/recognize-anything#160]
Hi, Is this commit https://github.com/xinyu1205/recognize-anything/commit/b85a8770a8c75bd7a508e97a328ebea7444917b7 has effect in the RAM performance?. Thanks

**Comment by xinyu1205** [comment]
This commit https://github.com/xinyu1205/recognize-anything/commit/b85a8770a8c75bd7a508e97a328ebea7444917b7 did not affect the performance.
