### ISSUE TITLE
一个tag对应tag_chinese多个标签，如"table"==“桌子/表格”，如何过滤标签

### ISSUE THREAD

**Issue by Agnets** [xinyu1205/recognize-anything#168]
您好！如果我识别一张图，含有书桌这个物体，能否在输出标签过滤“表格”，只输出“桌子”呢？我该如何修改？谢谢~

**Comment by xinyu1205** [comment]
可以改这个文件
https://github.com/xinyu1205/recognize-anything/blob/main/ram/data/ram_tag_list_chinese.txt

**Comment by Agnets** [comment]
首先，谢谢您的回复！可能是我描述不当，产生了歧义，非常抱歉。
是这样，我的需求是：如果输入一张仅含有“桌子”这个实物物体，我能否通过model识别到标签的词性或者根据语义信息，比如识别标签词性为“名词”或“动词”，或者根据单词在句子中的上下文来决定使用哪个翻译，如句子是 "Please put the book on the table."（请把书放在桌子上。），那么 "table" 应该翻译为“桌子”，而非“表格”这样。或者有没有更好的解决方案，期待您的回复~

**Comment by xinyu1205** [comment]
RAM和RAM++只能生成独立的tag
也许你可以尝试Tag2Text，Tag2Text可以根据丰富的tag来生成描述丰富的句子
例如tag是book， person， table。Tag2Text可以生成类似的句子：A person is putting the book on the table。

**Comment by Agnets** [comment]
真的真的非常感谢您的回复，不好意思再打扰一下呢~ 
是这样，我这边使用ram++得到独立标签，效果很棒，但是会出现一个英文tag对应有两三个中文标签（比如table，对应中文标签有“桌子”、“表格”等），这样就会使得描述图片识别的标签不完全准确。如果我需要输出更加准确的一个多义标签其中一个中文标签，比如输入一张图片（“一本书放在一个书桌上”），图片识别输出的tag有“book”“table”等，中文标签会有“书本”“桌子/表格”等，如果我只想输出中文标签会有“书本”“桌子”等（过滤掉“table”的中文标签“表格”）。请问我该如何修改，或者ram和ram++具有进一步过滤多义中文标签中的无关标签功能吗？最后，真的非常抱歉打扰了，期待您的回复~万分谢谢~

**Comment by xinyu1205** [comment]
目前没有类似的功能，因为RAM系列是英文模型，因此英译中，确实会存在一词多义的现象。

**Comment by Agnets** [comment]
好呢，明白了，谢谢您的回复~~
