### ISSUE TITLE
HuggingFace App is not working

### ISSUE THREAD

**Issue by meet244** [xinyu1205/recognize-anything#182]
![image](https://github.com/xinyu1205/recognize-anything/assets/83262693/57241080-b22e-4e74-a12f-d0f132ffea92)

**Comment by xinyu1205** [comment]
Thanks for your reminder, I have restart the hugging face demo.

**Comment by KJZhuAutomatic** [comment]
Thank you for your nice work! I also encountered the same issue with runtime error in hugging face demo. Really appreciate your prompt and excellent work in resolving this!
