### ISSUE TITLE
Unable to proceed with command 'pip install -e .'

### ISSUE THREAD

**Issue by Eunice-Wyy** [xinyu1205/recognize-anything#189]
## 🐛 Bug Report

ERROR: Failed building wheel for tokenizers
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects

## 🔬 How To Reproduce

1. Git clone the repo
2. Error when downloading command "pip install -e ."
    - have already downloaded Rust compiler (it was the first error which came up)

### Environment

* OS: Windows 
* Python version, get it with: 3.12.4

### Screenshots

1. When running the command:
![image](https://github.com/xinyu1205/recognize-anything/assets/144644083/69626eee-1a9d-4dce-a035-50c94caf6a2f)

**Comment by Rokkonrol** [comment]
```shell
pip install --upgrade setuptools
pip install -e .
```

_Originally posted by @HuAndrew in https://github.com/xinyu1205/recognize-anything/issues/107#issuecomment-1863927671_

**Comment by Eunice-Wyy** [comment]
I managed to solve it by recreating the conda environment with python version 3.8, thanks alot.
