### ISSUE TITLE
新tag处理有疑问

### ISSUE THREAD

**Issue by EricIrving-chs** [xinyu1205/recognize-anything#211]
您好，我在一个自己的新数据集上微调代码，tag_list也是新的。我看您的代码在微调时是self.label_embed = nn.Parameter(torch.zeros(self.num_class, q2l_config.encoder_width)) 这初始化为全0了，这似乎和您论文里的用clip离线得到embedidng不符合，全0开始微调是否会出现很大的问题，我是否该自己用离线的clip得到embedding.pth后再使用

**Comment by EricIrving-chs** [comment]
已解决，确实得用新的tag_list_embedding代替，不可以直接初始化为0，那样不能work

**Comment by LK-WordSnake** [comment]
@EricIrving-chs 你好请问一下要如何对自己的数据生成embedidng去替代呢

**Comment by EricIrving-chs** [comment]
> @EricIrving-chs 你好请问一下要如何对自己的数据生成embedidng去替代呢

论文使用的是clip text encoder，得到embedding矩阵后存下来然后导入

**Comment by LK-WordSnake** [comment]
> > @EricIrving-chs你好想问一下如何对自己的数据生成嵌入去替代呢
> 
> 论文使用的是剪辑文本编码器，得到嵌入矩阵后存下来导入然后

我进行了测试，但是输出shape 是[classes_num, 512]，没理解ram++里面的[4585 * 51, 512]是要怎么对齐

**Comment by EricIrving-chs** [comment]
> 我进行了测试，但是输出shape 是[classes_num, 512]，没理解ram++里面的[4585 * 51, 512]是要怎么对齐

我只复现了RAM，但是我想 51的含义就是51种不同的文本描述，你对每一个tag也用大模型生成51种表达就可以了。这个51应该也是可以自定义的

**Comment by LK-WordSnake** [comment]
> > 我进行了测试，但是输出shape是[classes_num, 512]，没理解ram++里面的[4585 * 51, 512]是要怎么对齐
> 
> 我只复现了RAM，但是我想51的含义就是51种不同的文本描述，你对每个标签也用大模型生成51种表达就可以了。这个51应该也自定义的可以

非常感谢你给出的帮助和灵感，我在Finetune中只是将代码中写死的部分更改为可变类别，完全没有注意到作者对label_embedding 进行了全0初始化，结果确实是不work的，loss始终在一个区间中徘徊没有下降，推理也是全词输出，我甚至以为是学习坍缩了[/lol]
