### ISSUE TITLE
Suggestion - update the pipeline to Fast-Sam in order to achieve real time inference

### ISSUE THREAD

**Issue by ofirkris** [xinyu1205/recognize-anything#51]
Reference - https://github.com/CASIA-IVA-Lab/FastSAM

<img width="831" alt="image" src="https://github.com/IDEA-Research/Grounded-Segment-Anything/assets/9070477/9dfd0b02-1d43-4aa0-b9ee-1be73029c971">

**Comment by xinyu1205** [comment]
Thank you for your recommendation! We will learn and consider it.
