### ISSUE TITLE
Request for Code: Text Semantic Parser for Tag Extraction

### ISSUE THREAD

**Issue by zjr2000** [xinyu1205/recognize-anything#69]
Hi there! First of all, thank you for sharing your code and models. I've been reading your paper and came across Section 3.2, where you mentioned using a text semantic parser to extract tags from raw captions. It would be immensely helpful if you could also share the code for the semantic parser. With access to this code, I'll be able to test your models on other datasets effectively. Thank you once again for your contribution!

**Comment by xinyu1205** [comment]
Hi, thanks for your attention! Open-source parsing code requires the approval process of the company. I recommend you directly use [SceneGraphParser](https://github.com/vacancy/SceneGraphParser) and refer section 3.2 of Tag2Text paper. Also, you can use GPT to extract tags from the text.
Welcome to provide feedback if you have more issues.

**Comment by zjr2000** [comment]
Thanks！
