### ISSUE TITLE
test benchmark ADE20k-clean

### ISSUE THREAD

**Issue by fmy7834** [xinyu1205/recognize-anything#84]
I appericate your work. Can you release the test benchmark ADE20k-clean?

**Comment by xinyu1205** [comment]
Hi, the labels of ADE20k-clean are:
animal
bag
hill
ball
step
bar
barrel
basket
bottle
plaything
clock
airplane
bench
path
bicycle
bed
bar
box
pier
bridge
sidewalk
lamp
light bulb
pool table
cabinet
cabinet
computer
boat
ship
sculpture
book
rug
land
pole
bookcase
seat
case
ceiling
chandelier
runway
wardrobe
apparel
building
coffee table
computer
bus
chest of drawers
sofa
counter
counter
countertop
curtain
cushion
bathtub
case
waterfall
stove
fence
fireplace
flag
car
pole
fountain
van
refrigerator
earth
hovel
ceiling fan
column
chandelier
mirror-stuff
chair
cup
table
desk
plate
dishwasher
door
railing
oven
palm tree
tank
field
armchair
flower
food
booth
pillow
trade name
canopy
plant pots
tower
runway
railing
person
sand
sand
cushion
awning
trade name
lake
microwave
shelf
shower
monitor
hovel
sink
mountain
sea
skyscraper
skyscraper
streetlight
stairway
booth
stool
stove
plant
minibike
poster
radiator
swimming pool
television receiver
river
road
rock
tent
ashcan
toilet
towel
land
armchair
signboard
tray
truck
sky
stage
vase
traffic light
waterfall
canopy
tree
water
windowpane

**Comment by fmy7834** [comment]
Wow, thank you!
